In [18]:
import numpy as np
import pandas as pd
from copy import deepcopy

In [19]:
def euclidean(a,b, ax=1):
    return np.linalg.norm(a-b, axis=ax)

In [43]:
def main():
    k = 3
    X = pd.read_csv('sushanth.csv',index_col=False)
    print(X)

    x1 = X['x1'].values
    x2 = X['y1'].values
    X = np.array(list(zip(x1, x2)))
    print(X)
    C_x = [6.2, 6.6 ,6.5]
    C_y = [3.2, 3.7, 3.0]
    Centroid = np.array(list(zip(C_x, C_y)), dtype=np.float32)
    print("Initial Centroids")
    print(Centroid.shape)

    Centroid_old = np.zeros(Centroid.shape)
    print(Centroid_old)
    # Cluster Lables(0, 1, 2)
    clusters = np.zeros(len(X))
    print(clusters)
    error = euclidean(Centroid, Centroid_old, None)
    print(error)
    iterr = 0
    # Loop will run till the error becomes zero
    while error != 0:
        # Assigning each value to its closest cluster
        iterr = iterr + 1
        for i in range(len(X)):
            print(X[i])
            distances = euclidean(X[i], Centroid)
            print(distances)
            cluster = np.argmin(distances)
            clusters[i] = cluster
            print(i)

        Centroid_old = deepcopy(Centroid)
        
        # Finding the new centroids by taking the Mean
        for p in range(k):
            points = [X[j] for j in range(len(X)) if clusters[j] == p]
            Centroid[p] = np.mean(points, axis=0)
        print(" Centre of the clusters after ", iterr," Iteration \n", Centroid)
        error = euclidean(Centroid, Centroid_old, None)
        print("Error  ... ",error)
        
if __name__ == "__main__": 
    main()

    x1   y1
0  5.9  3.2
1  4.6  2.9
2  6.2  2.8
3  4.7  3.2
4  5.5  4.2
5  5.0  3.0
6  4.9  3.1
7  6.7  3.1
8  5.1  3.8
[[5.9 3.2]
 [4.6 2.9]
 [6.2 2.8]
 [4.7 3.2]
 [5.5 4.2]
 [5.  3. ]
 [4.9 3.1]
 [6.7 3.1]
 [5.1 3.8]]
Initial Centroids
(3, 2)
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0.]
12.537144692236463
[5.9 3.2]
[0.29999981 0.86023248 0.63245553]
0
[4.6 2.9]
[1.62788188 2.15406585 1.90262976]
1
[6.2 2.8]
[0.40000005 0.98488579 0.36055513]
2
[4.7 3.2]
[1.49999981 1.96468819 1.81107703]
3
[5.5 4.2]
[1.22065541 1.20830449 1.56204994]
4
[5. 3.]
[1.21655233 1.74642485 1.5       ]
5
[4.9 3.1]
[1.30384029 1.80277556 1.60312195]
6
[6.7 3.1]
[0.50990215 0.60827632 0.2236068 ]
7
[5.1 3.8]
[1.25299622 1.50332954 1.61245155]
8
 Centre of the clusters after  1  Iteration 
 [[5.0333333 3.2      ]
 [5.5       4.2      ]
 [6.45      2.95     ]]
Error  ...  1.681104
[5.9 3.2]
[0.8666667  1.07703278 0.60415211]
0
[4.6 2.9]
[0.52704628 1.58113867 1.85067536]
1
[6.2 2.8]
[1.23333338 1.565