In [167]:
import pandas as pd
import numpy as np
import math

In [168]:
data=pd.read_csv('/home/root1/ML_1NT18IS058/StudentUniversitylogistic.csv')
data

x          y  z
0   34.623660  78.024693  0
1   30.286711  43.894998  0
2   35.847409  72.902198  0
3   60.182599  86.308552  1
4   79.032736  75.344376  1
..        ...        ... ..
95  83.489163  48.380286  1
96  42.261701  87.103851  1
97  99.315009  68.775409  1
98  55.340018  64.931938  1
99  74.775893  89.529813  1

[100 rows x 3 columns]

In [169]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   x       100 non-null    float64
 1   y       100 non-null    float64
 2   z       100 non-null    int64  
dtypes: float64(2), int64(1)
memory usage: 2.5 KB


In [170]:
x1=data['x'].values
x2=data['y'].values
y=data['z'].values

In [171]:
data.head()

x          y  z
0  34.623660  78.024693  0
1  30.286711  43.894998  0
2  35.847409  72.902198  0
3  60.182599  86.308552  1
4  79.032736  75.344376  1

In [172]:
X = data.iloc[:,0:2]
X

x          y
0   34.623660  78.024693
1   30.286711  43.894998
2   35.847409  72.902198
3   60.182599  86.308552
4   79.032736  75.344376
..        ...        ...
95  83.489163  48.380286
96  42.261701  87.103851
97  99.315009  68.775409
98  55.340018  64.931938
99  74.775893  89.529813

[100 rows x 2 columns]

In [173]:
Y = data.iloc[:,-1]
Y

0     0
1     0
2     0
3     1
4     1
     ..
95    1
96    1
97    1
98    1
99    1
Name: z, Length: 100, dtype: int64

In [174]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)
y_train

79    0
61    0
20    0
19    1
17    0
     ..
67    0
54    0
24    1
55    0
28    0
Name: z, Length: 80, dtype: int64

In [175]:
X = data.iloc[:,0:2]
print(X)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(X)
print(scaler)
print(scaler.mean_)
X = scaler.transform(X)

            x          y
0   34.623660  78.024693
1   30.286711  43.894998
2   35.847409  72.902198
3   60.182599  86.308552
4   79.032736  75.344376
..        ...        ...
95  83.489163  48.380286
96  42.261701  87.103851
97  99.315009  68.775409
98  55.340018  64.931938
99  74.775893  89.529813

[100 rows x 2 columns]
StandardScaler()
[65.64427406 66.22199809]


In [176]:
X_train1 = X_train['x'].values
X_train1

array([82.22666158, 35.28611282, 67.37202755, 76.97878373, 67.94685548,
       90.44855097, 77.19303493, 34.62365962, 61.37928945, 78.63542435,
       99.8278578 , 44.66826172, 79.03273605, 51.04775177, 54.63510555,
       97.64563396, 85.40451939, 42.26170081, 68.46852179, 51.54772027,
       90.54671411, 97.77159928, 52.34800399, 99.27252693, 32.57720017,
       75.01365839, 69.36458876, 89.67677575, 35.84740877, 74.24869137,
       60.45788574, 89.84580671, 82.36875376, 74.775893  , 52.04540477,
       83.90239366, 69.07014406, 50.4581598 , 75.39561147, 62.0730638 ,
       34.18364003, 95.86155507, 88.91389642, 67.31925747, 70.66150955,
       55.34001756, 91.5649745 , 34.52451385, 75.47770201, 75.02474557,
       53.97105215, 79.94481794, 32.72283304, 45.08327748, 61.10666454,
       62.22267576, 94.83450672, 80.19018075, 64.17698887, 74.78925296,
       60.18259939, 72.34649423, 56.2538175 , 55.48216114, 93.1143888 ,
       83.48916274, 38.7858038 , 71.79646206, 99.31500881, 60.45

In [177]:
X_train2 = X_train['y'].values
X_train2

array([42.71987854, 47.02051395, 42.83843832, 47.57596365, 46.67857411,
       87.50879176, 70.4582    , 78.02469282, 72.80788731, 96.64742717,
       72.36925193, 66.45008615, 75.34437644, 45.82270146, 52.21388588,
       68.86157272, 57.05198398, 87.10385094, 85.5943071 , 46.85629026,
       43.39060181, 86.72782233, 60.76950526, 60.999031  , 95.59854761,
       30.60326323, 97.71869196, 65.79936593, 72.90219803, 69.82457123,
       73.0949981 , 45.35828361, 40.61825516, 89.5298129 , 69.43286012,
       56.30804622, 52.74046973, 75.80985953, 85.75993667, 96.76882412,
       75.23772034, 38.22527806, 69.8037889 , 66.58935318, 92.92713789,
       64.93193801, 88.69629255, 60.39634246, 90.424539  , 46.55401354,
       89.20735014, 74.16311935, 43.30717306, 56.31637178, 96.51142588,
       52.06099195, 45.6943068 , 44.82162893, 80.90806059, 41.57341523,
       86.3085521 , 96.22759297, 39.26147251, 35.57070347, 38.80067034,
       48.3802858 , 64.99568096, 78.45356225, 68.77540947, 42.50

In [178]:
X_train3 = data['z'].values
X_train3

array([0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1])

In [179]:
b0=0.0
b1=0.0
b2=0.0

In [180]:
for j in range(0,80):
    print(X_train1[j],X_train2[j])

82.22666158 42.71987854
35.28611282 47.02051395
67.37202755 42.83843832
76.97878373 47.57596365
67.94685548 46.67857411
90.44855097 87.50879176
77.19303493 70.4582
34.62365962 78.02469282
61.37928945 72.80788731
78.63542435 96.64742717
99.8278578 72.36925193
44.66826172 66.45008615
79.03273605 75.34437644
51.04775177 45.82270146
54.63510555 52.21388588
97.64563396 68.86157272
85.40451939 57.05198398
42.26170081 87.10385094
68.46852179 85.5943071
51.54772027 46.85629026
90.54671411 43.39060181
97.77159928 86.72782233
52.34800399 60.76950526
99.27252693 60.999031
32.57720017 95.59854761
75.01365839 30.60326323
69.36458876 97.71869196
89.67677575 65.79936593
35.84740877 72.90219803
74.24869137 69.82457123
60.45788574 73.0949981
89.84580671 45.35828361
82.36875376 40.61825516
74.775893 89.5298129
52.04540477 69.43286012
83.90239366 56.30804622
69.07014406 52.74046973
50.4581598 75.80985953
75.39561147 85.75993667
62.0730638 96.76882412
34.18364003 75.23772034
95.86155507 38.22527806
88.913

In [181]:
y_train = np.array(y_train)
y_train

array([0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0])

In [182]:
y1 = b0 +b1*X_train1+ b2*X_train2
y_pred1 = 1 / (1 + np.exp(-y1))

In [183]:
y = b0 +b1*X_train1[j]+ b2*X_train2[j]
pred = 1 /(1 + np.exp(-y))
b0 = b0 + 0.01*(y_train[j]-pred)*pred*(1-pred)*1
b1 = b1 + 0.01*(y_train[j]-pred)*pred*(1-pred)*X_train1[j]
b2 = b2 + 0.01*(y_train[j]-pred)*pred*(1-pred)*X_train2[j]

In [184]:
pred

0.5

In [185]:
db0 = -2* sum((y_train-pred)*pred*(1-pred))
db1 = -2*sum((y_train-pred)*pred*(1-pred)*X_train1)
db2 = -2*sum((y_train-pred)*pred*(1-pred)*X_train2)

In [186]:
L = 0.001
b0 = b0 - L*db0
b1 = b1 - L*db1
b2 = b2 - L*db2

In [187]:
b0

0.0032500000000000003

In [188]:
b1

0.42150157724249987

In [189]:
b2

0.4301179006425002

In [190]:
y_test

42    1
68    1
76    1
1     0
74    1
22    0
83    1
14    0
36    0
63    0
93    1
23    0
84    1
12    1
65    0
25    1
32    0
9     1
71    1
86    0
Name: z, dtype: int64

In [191]:
X_test1 = X_test['x'].values
X_test2 = X_test['y'].values
X_test1

array([94.44336777, 80.27957401, 47.26426911, 30.28671077, 58.84095622,
       50.53478829, 57.23870632, 39.53833914, 33.91550011, 30.05882245,
       74.49269242, 34.21206098, 80.366756  , 82.30705337, 66.56089447,
       62.27101367, 52.10797973, 84.43281996, 64.03932042, 42.07545454])

In [192]:
X_test2

array([65.56892161, 92.11606081, 88.475865  , 43.89499752, 75.85844831,
       48.85581153, 59.51428198, 76.03681085, 98.86943574, 49.59297387,
       84.84513685, 44.2095286 , 90.9601479 , 76.4819633 , 41.09209808,
       69.95445795, 63.12762377, 43.53339331, 78.03168802, 78.844786  ])

In [193]:
from sklearn.metrics import accuracy_score


In [194]:
ypred_test = b0 +b1*X_test1+ b2*X_test2
y_pred = 1 /(1 + np.exp(-ypred_test))
print(accuracy_score(y_test,np.round(y_pred)))


0.55
